spring.application.name=ai-notes-assistant

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5:3b

spring.ai.ollama.embedding.options.model=nomic-embed-text

spring.datasource.url=jdbc:postgresql://localhost:5433/ai_notes
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.ai.vectorstore.pgvector.initialize-schema=true

spring.ai.vectorstore.pgvector.dimensions=768
